In [1]:
# Let printing work the same in Python 2 and 3
from __future__ import print_function

# NumPy
The NumPy package provides the "ndarray" object. The NumPy array is used to contain data of uniform type with an arbitrary number of dimensions. NumPy then provides basic mathematical and array methods to lay down the foundation for the entire SciPy ecosystem. The following import statement is the generally accepted convention for NumPy.

In [1]:
import numpy as np

## Array Creation
There are several ways to make NumPy arrays. An array has three particular attributes that can be queried: shape, size and the number of dimensions.

In [15]:
a = np.array([1, 2, 3])
print(a.shape)
print(a.size)
print(a.ndim)
b=a.transpose()
print(b.shape)

(3,)
3
1
(3,)


In [36]:
x = np.arange(100)
print(x.shape)
print(x.size)
print(x.ndim)
print(x)

(100,)
100
1
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [40]:
y = np.random.rand(5, 80)
print(y.shape)
print(y.size)
print(y.ndim)
print(y)

(5, 80)
400
2
[[0.53976834 0.74040017 0.60774894 0.48335797 0.72670459 0.09542809
  0.92371023 0.30969364 0.20269984 0.63148171 0.30737192 0.38399603
  0.90989083 0.23469531 0.24493916 0.44153159 0.53218192 0.30861953
  0.43140631 0.80528323 0.74619187 0.73263286 0.99825384 0.07110721
  0.43923302 0.11118348 0.10956198 0.30666863 0.4850785  0.06216407
  0.57749652 0.78280188 0.52891739 0.8345146  0.2702637  0.45994002
  0.42639373 0.30529609 0.47923413 0.27916406 0.16636014 0.916748
  0.44689994 0.64899408 0.57759684 0.96451579 0.10525828 0.43003412
  0.52007613 0.63362325 0.84631071 0.92707566 0.60913065 0.57063806
  0.41330345 0.68859375 0.32432644 0.14882283 0.02508426 0.03901282
  0.08260899 0.592899   0.4078573  0.12350852 0.06345991 0.0739343
  0.77758295 0.92017577 0.23134375 0.79580576 0.40725374 0.29663164
  0.44429166 0.43370689 0.81021611 0.71404654 0.62040495 0.94802956
  0.26288242 0.22803395]
 [0.70835577 0.83336176 0.75744563 0.74049156 0.46117948 0.58122888
  0.27614937

## Array Manipulation
How to change the shape of an array without a copy!

In [38]:
x.shape = (20, 5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]]


NumPy can even automatically figure out the size of at most one dimension for you.

In [45]:
y.shape = (4, 20, -1)
print(y.shape)
print(y)

(4, 20, 5)
[[[0.53976834 0.74040017 0.60774894 0.48335797 0.72670459]
  [0.09542809 0.92371023 0.30969364 0.20269984 0.63148171]
  [0.30737192 0.38399603 0.90989083 0.23469531 0.24493916]
  [0.44153159 0.53218192 0.30861953 0.43140631 0.80528323]
  [0.74619187 0.73263286 0.99825384 0.07110721 0.43923302]
  [0.11118348 0.10956198 0.30666863 0.4850785  0.06216407]
  [0.57749652 0.78280188 0.52891739 0.8345146  0.2702637 ]
  [0.45994002 0.42639373 0.30529609 0.47923413 0.27916406]
  [0.16636014 0.916748   0.44689994 0.64899408 0.57759684]
  [0.96451579 0.10525828 0.43003412 0.52007613 0.63362325]
  [0.84631071 0.92707566 0.60913065 0.57063806 0.41330345]
  [0.68859375 0.32432644 0.14882283 0.02508426 0.03901282]
  [0.08260899 0.592899   0.4078573  0.12350852 0.06345991]
  [0.0739343  0.77758295 0.92017577 0.23134375 0.79580576]
  [0.40725374 0.29663164 0.44429166 0.43370689 0.81021611]
  [0.71404654 0.62040495 0.94802956 0.26288242 0.22803395]
  [0.70835577 0.83336176 0.75744563 0.7404915

## Array Indexing

In [48]:
# Scalar Indexing
print(x[2][:])

[10 11 12 13 14]


In [31]:
# Slicing
print(x[2:5])

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [58]:
# Advanced slicing
print("First 5 rows\n", x[:5])
print("Row 18 to the end\n", x[18:])
print("Last 5 rows\n", x[-5:])
print("Reverse the rows\n", x[::-1])

First 5 rows
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Row 18 to the end
 [[90 91 92 93 94]
 [95 96 97 98 99]]
Last 5 rows
 [[75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]]
Reverse the rows
 [[95 96 97 98 99]
 [90 91 92 93 94]
 [85 86 87 88 89]
 [80 81 82 83 84]
 [75 76 77 78 79]
 [70 71 72 73 74]
 [65 66 67 68 69]
 [60 61 62 63 64]
 [55 56 57 58 59]
 [50 51 52 53 54]
 [45 46 47 48 49]
 [40 41 42 43 44]
 [35 36 37 38 39]
 [30 31 32 33 34]
 [25 26 27 28 29]
 [20 21 22 23 24]
 [15 16 17 18 19]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]]


In [33]:
# Boolean Indexing
print(x[(x % 2) == 0])

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [34]:
# Fancy Indexing -- Note the use of a list, not tuple!
print(x[[1, 3, 8, 9, 2]])

[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [10 11 12 13 14]]


## Broadcasting
Broadcasting is a very useful feature of NumPy that will let arrays with differing shapes still be used together. In most cases, broadcasting is faster, and it is more memory efficient than the equivalent full array operation.

In [49]:
print("Shape of X:", x.shape)
print("Shape of Y:", y.shape)

Shape of X: (20, 5)
Shape of Y: (4, 20, 5)


Now, here are three identical assignments. The first one takes full advantage of broadcasting by allowing NumPy to automatically add a new dimension to the *left*. The second explicitly adds that dimension with the special NumPy alias "np.newaxis". These first two creates a singleton dimension without any new arrays being created. That singleton dimension is then implicitly tiled, much like the third example to match with the RHS of the addition operator. However, unlike the third example, the broadcasting merely re-uses the existing data in memory.

In [59]:
# Broadcasting: numpy aggiunge da solo una dimensione a sinistra
a = x + y
print(a.shape)
# Aggiungo un nuovo asse
b = x[np.newaxis, :, :] + y
print(b.shape)
# prendi le dimensioni y e z di x e le ricopi nella dimensione x (e volte)
c = np.tile(x, (4, 1, 1)) + y
print(c.shape)
print("Are a and b identical?", np.all(a == b))
print("Are a and c identical?", np.all(a == c))
print(a)

(4, 20, 5)
(4, 20, 5)
(4, 20, 5)
Are a and b identical? True
Are a and c identical? True
[[[ 0.53976834  1.74040017  2.60774894  3.48335797  4.72670459]
  [ 5.09542809  6.92371023  7.30969364  8.20269984  9.63148171]
  [10.30737192 11.38399603 12.90989083 13.23469531 14.24493916]
  [15.44153159 16.53218192 17.30861953 18.43140631 19.80528323]
  [20.74619187 21.73263286 22.99825384 23.07110721 24.43923302]
  [25.11118348 26.10956198 27.30666863 28.4850785  29.06216407]
  [30.57749652 31.78280188 32.52891739 33.8345146  34.2702637 ]
  [35.45994002 36.42639373 37.30529609 38.47923413 39.27916406]
  [40.16636014 41.916748   42.44689994 43.64899408 44.57759684]
  [45.96451579 46.10525828 47.43003412 48.52007613 49.63362325]
  [50.84631071 51.92707566 52.60913065 53.57063806 54.41330345]
  [55.68859375 56.32432644 57.14882283 58.02508426 59.03901282]
  [60.08260899 61.592899   62.4078573  63.12350852 64.06345991]
  [65.0739343  66.77758295 67.92017577 68.23134375 69.79580576]
  [70.40725374 

In [66]:
x = np.array((11,10))
y = np.array((3,11,10))
x+y

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [92]:
np.ogrid[0:5,0:5][0].shape

(5, 1)

In [117]:
A=np.matrix([1, 2, 3]).T
type(A)
A

matrix([[1],
        [2],
        [3]])

Another example of broadcasting two 1-D arrays to make a 2-D array.

In [71]:
x = np.arange(-5, 5, 0.1)
y = np.arange(-8, 8, 0.25)
print(x.shape, y.shape)
z = x[np.newaxis, :] * y[:, np.newaxis]
# z = x + y
print(z.shape)
#print(x)

(100,) (64,)
(64, 100)


In [44]:
# More concisely
y, x = np.ogrid[-8:8:0.25, -5:5:0.1]
print(x.shape, y.shape)
z = x * y
print(z.shape)
#print(x)

(1, 100) (64, 1)
(64, 100)
[[-5.  -4.9 -4.8 -4.7 -4.6 -4.5 -4.4 -4.3 -4.2 -4.1 -4.  -3.9 -3.8 -3.7
  -3.6 -3.5 -3.4 -3.3 -3.2 -3.1 -3.  -2.9 -2.8 -2.7 -2.6 -2.5 -2.4 -2.3
  -2.2 -2.1 -2.  -1.9 -1.8 -1.7 -1.6 -1.5 -1.4 -1.3 -1.2 -1.1 -1.  -0.9
  -0.8 -0.7 -0.6 -0.5 -0.4 -0.3 -0.2 -0.1  0.   0.1  0.2  0.3  0.4  0.5
   0.6  0.7  0.8  0.9  1.   1.1  1.2  1.3  1.4  1.5  1.6  1.7  1.8  1.9
   2.   2.1  2.2  2.3  2.4  2.5  2.6  2.7  2.8  2.9  3.   3.1  3.2  3.3
   3.4  3.5  3.6  3.7  3.8  3.9  4.   4.1  4.2  4.3  4.4  4.5  4.6  4.7
   4.8  4.9]]
